apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: service-name
    - name: namespace
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: result >= 0.90
      failureLimit: 3
      provider:
        prometheus:
          address: http://observability-kube-prometh-prometheus.monitoring:9090
          # Use simple pod availability check first since we have no traffic generator yet.
          # This checks: "Are there any pods for this app that are NOT ready?" -> If 0, success.
          # Real query would need traffic. For lab, lets use 'up'.
          # Wait, user wants failure injection. 'up' is hard to fail via HTTP chaos.
          # Let's stick to the Ingress query but make it robust.
          # If no traffic, valid result is NaN? We set default 1 (100%).
          query: |
            (
              sum(rate(nginx_ingress_controller_requests{exported_service=~".*{{args.service-name}}", namespace="{{args.namespace}}", status!~"5.*"}[1m])) 
              / 
              sum(rate(nginx_ingress_controller_requests{exported_service=~".*{{args.service-name}}", namespace="{{args.namespace}}"}[1m]))
            ) or vector(1)
