apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: success-rate-global
spec:
  args:
    - name: service-name
    - name: namespace
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: result >= 0.90
      failureLimit: 3
      provider:
        prometheus:
          address: http://observability-kube-prometh-prometheus.monitoring:9090
          # Check HTTP success rate via Ingress metrics
          query: |
            (
              sum(rate(nginx_ingress_controller_requests{exported_service=~".*{{args.service-name}}", namespace="{{args.namespace}}", status!~"5.*"}[1m])) 
              / 
              sum(rate(nginx_ingress_controller_requests{exported_service=~".*{{args.service-name}}", namespace="{{args.namespace}}"}[1m]))
            ) or vector(1)
